# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    if Vagrant.has_plugin? "vagrant-vbguest"
        config.vbguest.no_install = true
        config.vbguest.auto_update = false
        config.vbguest.no_remote = true
    end
    
    config.vm.define "servidorHAproxy" do |servidorHAproxy|
        servidorHAproxy.vm.box = "bento/ubuntu-22.04"
        servidorHAproxy.vm.network :private_network, ip: "192.168.100.8"
        servidorHAproxy.vm.provision "shell", path: "script.sh"
        servidorHAproxy.vm.hostname = "haproxy"
    end
end
